language: node_js

node_js:
   "14.5.0"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  email: surya.socialnetworking@gmail.com
  name: Surya Raj
  target-branch: master
  on:
    branch: develop
